In [10]:
import gym
import numpy as np
import random
from IPython.display import clear_output
env = gym.make('FrozenLake-v0')
Q = np.zeros([env.nS, env.nA])
alpha = 0.01
gamma = 1

for i in range(1, 300001):
    state = env.reset()
    epochs, reward, = 0, 0
    done = False
    action = env.action_space.sample() 
    while not done:
        next_state, reward, done, info = env.step(action)
        next_action = env.action_space.sample() 
        if done:
            Q[state,action] = (1 - alpha) * Q[state,action] + alpha * (reward)
        else:
            Q[state,action] = (1 - alpha) * Q[state,action] + alpha * (reward + gamma * Q[next_state,next_action])
        state = next_state
        action = next_action
        epochs = epochs + 1
    if i % 100 == 0:
        clear_output(wait=True)
        print('Episode: {0}'.format(i))
print("Training finished.\n")


print("Q-function:")
print(Q)


random_policy = np.ones([env.nS, env.nA]) / env.nA
V = np.zeros(env.nS)
for s in range(env.nS):
    for a in range(env.nA):
        V[s] = V[s] + random_policy[s,a] * Q[s,a]
print("Value function:")                      
print(V)

Episode: 300000
Training finished.

Q-function:
[[0.01461424 0.01398789 0.0131608  0.01264194]
 [0.00741789 0.01052473 0.01002933 0.01446312]
 [0.02166435 0.02103929 0.02116748 0.01352727]
 [0.00957021 0.0095984  0.0069297  0.01224244]
 [0.02122314 0.01652028 0.01585131 0.01036036]
 [0.         0.         0.         0.        ]
 [0.05132546 0.04755657 0.04916686 0.00675574]
 [0.         0.         0.         0.        ]
 [0.01618288 0.03821769 0.03627472 0.0488777 ]
 [0.06980008 0.1064766  0.09321511 0.05044041]
 [0.16184612 0.17436988 0.14046497 0.04154171]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.08098459 0.18253375 0.23610153 0.16140433]
 [0.22033115 0.49944121 0.46713118 0.43138571]
 [0.         0.         0.         0.        ]]
Value function:
[0.01360122 0.01060877 0.0193496  0.00958519 0.01598877 0.
 0.03870116 0.         0.03488825 0.07998305 0.12955567 0.
 0.         0.16525605 0.40457231 0.        ]
