In [1]:
import gym
import numpy as np
env = gym.make('FrozenLake-v1')
env.render()

def QVI(env, discount_factor=1.0, theta=0.00001):

    Q = np.zeros([env.nS, env.nA])
    while True:
        delta = 0
        # For each state, perform a "full backup"
        for s in range(env.nS):
            q = np.zeros(env.nA)
            for a in range(env.nA):
                for  prob, next_state, reward, done in env.P[s][a]:
                    q[a] = q[a] + prob * (reward + discount_factor * np.max(Q[next_state]))
                delta = max(delta, np.abs(q[a] - Q[s][a]))
            for i in range(env.nA):
                Q[s][i] = q[i]
        if delta < theta:
            break
    return np.array(Q)

q = QVI(env)
print("Q value Function:")
print(q)
print("")
pi = np.zeros(env.nS)
for s in range(env.nS):
    pi[s] = np.argmax(q[s])
print("Pi policy Function:")
print(pi)
print("")

done = False
nA = env.action_space.n
state = env.reset()
env.render()
while not done:
    action = np.argmax(q[state])
    new_state, reward, done, info = env.step(action)
    env.render()
    state = new_state


SFFF
FHFH
FFFH
HFFG
Q value Function:
[[0.82336142 0.82334241 0.82334241 0.82333659]
 [0.54888666 0.54887345 0.5488525  0.82330631]
 [0.72528616 0.72527944 0.72526365 0.823268  ]
 [0.54883559 0.54883559 0.54882584 0.82324851]
 [0.82337832 0.54892451 0.54892063 0.5489115 ]
 [0.         0.         0.         0.        ]
 [0.52929722 0.25487455 0.52929722 0.27442267]
 [0.         0.         0.         0.        ]
 [0.54892626 0.54894534 0.54893796 0.82340479]
 [0.56856417 0.82343872 0.54897046 0.52934281]
 [0.76462641 0.588194   0.49014683 0.45091198]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.56857548 0.60781034 0.88228991 0.588194  ]
 [0.86268653 0.9411444  0.90192323 0.88230544]
 [0.         0.         0.         0.        ]]

Pi policy Function:
[0. 3. 3. 3. 0. 0. 0. 0. 3. 1. 0. 0. 0. 2. 1. 0.]


SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG